{"implements":[],"javadoc":"<code>FileInUseException<\/code> indicates that there was contention\n for a file which is in-use.  This can be caused for various reasons\n including a file lock of some kind.","static":false,"extends":"java.io.IOException","methods":[{"javadoc":"Create a new FileInUseException with the given message.\n@param msg the exception message.","static":false,"name":"<init>","comment":"Create a new FileInUseException with the given message.","params":[{"type_long":"java.lang.String","name":"msg","comment":"the exception message.","type_short":"String"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"Create a new FileInUseException with the given message and cause.\n@param msg the exception message.","static":false,"name":"<init>","comment":"Create a new FileInUseException with the given message and cause.","params":[{"type_long":"java.lang.String","name":"msg","comment":"the exception message.","type_short":"String"},{"type_long":"java.lang.Throwable","name":"cause","comment":"","type_short":"Throwable"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}}],"name":"FileInUseException","comment":"FileInUseException indicates that there was contention\n for a file which is in-use.  This can be caused for various reasons\n including a file lock of some kind.","fields":[]}
