{"implements":[],"javadoc":"<code>DataDirectoryException<\/code> is thrown when a folder item can not be \n created because its associated data directory already exists.","static":false,"extends":"java.io.IOException","methods":[{"javadoc":"Constructor.\n@param msg error message\n@param dir existing data directory","static":false,"name":"<init>","comment":"Constructor.","params":[{"type_long":"java.lang.String","name":"msg","comment":"error message","type_short":"String"},{"type_long":"java.io.File","name":"dir","comment":"existing data directory","type_short":"File"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"Returns existing data directory","static":false,"name":"getDataDirectory","comment":"Returns existing data directory","params":[],"throws":[],"return":{"type_long":"java.io.File","comment":"","type_short":"File"}}],"name":"DataDirectoryException","comment":"DataDirectoryException is thrown when a folder item can not be \n created because its associated data directory already exists.","fields":[{"type_long":"java.io.File","javadoc":"","static":false,"name":"dir","comment":"","type_short":"File","constant_value":null}]}
